#ifndef LIBFACESERVICEJAVA_GLOBAL_H
#define LIBFACESERVICEJAVA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBFACESERVICEJAVA_LIBRARY)
#  define LIBFACESERVICEJAVASHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBFACESERVICEJAVASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBFACESERVICEJAVA_GLOBAL_H
