/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_smart_ai_face_service_FaceService */

#ifndef _Included_cn_smart_ai_face_service_FaceService
#define _Included_cn_smart_ai_face_service_FaceService
#ifdef __cplusplus
extern "C" {
#endif
#undef cn_smart_ai_face_service_FaceService_NoError
#define cn_smart_ai_face_service_FaceService_NoError 0L
#undef cn_smart_ai_face_service_FaceService_NetworkInternalErr
#define cn_smart_ai_face_service_FaceService_NetworkInternalErr -1L
#undef cn_smart_ai_face_service_FaceService_ImageNotExist
#define cn_smart_ai_face_service_FaceService_ImageNotExist -2L
#undef cn_smart_ai_face_service_FaceService_ImageFormatErr
#define cn_smart_ai_face_service_FaceService_ImageFormatErr -3L
#undef cn_smart_ai_face_service_FaceService_ImageSizeErr
#define cn_smart_ai_face_service_FaceService_ImageSizeErr -4L
#undef cn_smart_ai_face_service_FaceService_ImageBroken
#define cn_smart_ai_face_service_FaceService_ImageBroken -5L
#undef cn_smart_ai_face_service_FaceService_ImageSizeSmall
#define cn_smart_ai_face_service_FaceService_ImageSizeSmall -6L
#undef cn_smart_ai_face_service_FaceService_FaceNotProperAngle
#define cn_smart_ai_face_service_FaceService_FaceNotProperAngle -7L
#undef cn_smart_ai_face_service_FaceService_FaceGroupNotExist
#define cn_smart_ai_face_service_FaceService_FaceGroupNotExist -8L
#undef cn_smart_ai_face_service_FaceService_FaceGroupAlreadyExist
#define cn_smart_ai_face_service_FaceService_FaceGroupAlreadyExist -9L
#undef cn_smart_ai_face_service_FaceService_FaceDatabaseDirNotExist
#define cn_smart_ai_face_service_FaceService_FaceDatabaseDirNotExist -10L
#undef cn_smart_ai_face_service_FaceService_CannotCreateFaceGroupDir
#define cn_smart_ai_face_service_FaceService_CannotCreateFaceGroupDir -11L
#undef cn_smart_ai_face_service_FaceService_OtherErr
#define cn_smart_ai_face_service_FaceService_OtherErr -12L
#undef cn_smart_ai_face_service_FaceService_UnabletoapplyforFRresources
#define cn_smart_ai_face_service_FaceService_UnabletoapplyforFRresources -13L
#undef cn_smart_ai_face_service_FaceService_UnabletoapplyforFDresources
#define cn_smart_ai_face_service_FaceService_UnabletoapplyforFDresources -14L
#undef cn_smart_ai_face_service_FaceService_FaceserviceNotinit
#define cn_smart_ai_face_service_FaceService_FaceserviceNotinit -15L
/*
 * Class:     cn_smart_ai_face_service_FaceService
 * Method:    init
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_smart_ai_face_service_FaceService_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_smart_ai_face_service_FaceService
 * Method:    addfacegroup
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_smart_ai_face_service_FaceService_addfacegroup
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_smart_ai_face_service_FaceService
 * Method:    detectface
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_smart_ai_face_service_FaceService_detectface
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_smart_ai_face_service_FaceService
 * Method:    identifyface
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_smart_ai_face_service_FaceService_identifyface
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_smart_ai_face_service_FaceService
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_smart_ai_face_service_FaceService_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
