#ifndef LIBFACESERVICE_GLOBAL_H
#define LIBFACESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBFACESERVICE_LIBRARY)
#  define LIBFACESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBFACESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBFACESERVICE_GLOBAL_H
